# Generated by Django 5.2 on 2025-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                editable=False, max_length=16, primary_key=True, serialize=False
            ),
        ),
    ]
